logging:
  level:
    com:
      yun:
        dao: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yun.entity
spring:
  cache:
    cache-names: zykCache
    type: redis
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/springall?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    cluster:
      nodes: 192.168.230.180:7001,192.168.230.180:7002,192.168.230.180:7003,192.168.230.180:7004,192.168.230.180:7005,192.168.230.180:7006,192.168.230.180:7007,192.168.230.180:7008
